export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const REAUTHENTICATE_REQUEST = 'REAUTHENTICATE_REQUEST'
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS'
export const REAUTHENTICATE_ERROR = 'REAUTHENTICATE_ERROR'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'
