# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('learn', 'learn'), ('teach', 'teach')], max_length=5),
        ),
    ]
