# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.CharField(choices=[('AnfängerIn', 'AnfängerIn'), ('Fortgeschritten', 'Fortgeschritten'), ('Platt-Profi', 'Platt-Profi')], default='AnfängerIn', max_length=120),
        ),
    ]
